version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: reglito
      POSTGRES_PASSWORD: reglito
      POSTGRES_DB: reglito_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
